// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/dbclaimoperator/v1alpha1.DatabaseClaim":          schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseClaim(ref),
		"./pkg/apis/dbclaimoperator/v1alpha1.DatabaseClaimSpec":      schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseClaimSpec(ref),
		"./pkg/apis/dbclaimoperator/v1alpha1.DatabaseClaimStatus":    schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseClaimStatus(ref),
		"./pkg/apis/dbclaimoperator/v1alpha1.DatabaseInstance":       schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseInstance(ref),
		"./pkg/apis/dbclaimoperator/v1alpha1.DatabaseInstanceSpec":   schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseInstanceSpec(ref),
		"./pkg/apis/dbclaimoperator/v1alpha1.DatabaseInstanceStatus": schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseInstanceStatus(ref),
	}
}

func schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseClaim(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DatabaseClaim is the Schema for the databaseclaims API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/dbclaimoperator/v1alpha1.DatabaseClaimSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/dbclaimoperator/v1alpha1.DatabaseClaimStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/dbclaimoperator/v1alpha1.DatabaseClaimSpec", "./pkg/apis/dbclaimoperator/v1alpha1.DatabaseClaimStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseClaimSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DatabaseClaimSpec defines the desired state of DatabaseClaim",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"secretName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"databaseInstanceName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"databaseInstanceName"},
			},
		},
	}
}

func schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseClaimStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DatabaseClaimStatus defines the observed state of DatabaseClaim",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseInstance(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DatabaseInstance is the Schema for the databaseinstances API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/dbclaimoperator/v1alpha1.DatabaseInstanceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/dbclaimoperator/v1alpha1.DatabaseInstanceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/dbclaimoperator/v1alpha1.DatabaseInstanceSpec", "./pkg/apis/dbclaimoperator/v1alpha1.DatabaseInstanceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseInstanceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DatabaseInstanceSpec defines the desired state of DatabaseInstance",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"unoperatedInstance": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/dbclaimoperator/v1alpha1.UnoperatedInstance"),
						},
					},
				},
				Required: []string{"unoperatedInstance"},
			},
		},
		Dependencies: []string{
			"./pkg/apis/dbclaimoperator/v1alpha1.UnoperatedInstance"},
	}
}

func schema_pkg_apis_dbclaimoperator_v1alpha1_DatabaseInstanceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "DatabaseInstanceStatus defines the observed state of DatabaseInstance",
				Type:        []string{"object"},
			},
		},
	}
}
